### ISSUE TITLE
* SCRATCH *

### ISSUE THREAD

**Issue by ebanner** [ebanner/awakened-bot#1]
# TODO

- [x] Send a test message

# MVP

What is the MVP?

If anyone adds an emoji reaction to a message I myself added an emoji reaction to, get notified

The thing is that now that I've emoji reacted to that message, I want to be notified what happens from here onwards

Hmm

Almost like if there was a "my messages" master list of messages, I could check every reaction emoji and compare it against that

Instead, let's just look up the message on the fly and see if I have an emoji reaction in there

## Alerting

- [ ] Alert you when an emoji is added

## Finding info about the message

- [x] Get reaction information about that message
- [x] Find out the other users who have added the same emoji to that message
- [x] Find other users who have added all emojis to that message
- [x] Map user ID to user

^ follow a hello world python app for this, so we have a foundation to build off

This is terrible, there should be a visual programming way to do this

## Links

- https://api.slack.com/apps
- https://medium.com/glasswall-engineering/how-to-create-a-slack-bot-using-aws-lambda-in-1-hour-1dbc1b6f021c
- https://api.slack.com/start/building/bolt-python
- https://slack.dev/bolt-python/tutorial/getting-started

## HTTP API

Testing locally

https://api.slack.com/apis/connections/events-api#prepare
